---
# tasks file for ubuntu-juniper-vpn

- name: Update Ubuntu Java alternatives
  command: update-alternatives --install /usr/bin/java java {{ JAVA_BIN }} 10
  tags:
    - java

- name: Install 32 bit libs for NC.jar
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - libstdc++6:i386
    - lib32z1
    - lib32ncurses5
    - lib32bz2-1.0
    - libxext6:i386
    - libxrender1:i386
    - libxtst6:i386
    - libxi6:i386
   tags:
    - libs

- name: Checkout jvpn from Github
  git: repo:https://github.com/exemaitch/jvpn.git dest=/opt/jvpn
  tags:
    - checkout-jvpn

- name: Install JVPN Perl Depdendency
  apt: name={{ item }} state=present
    - libterm-readkey-perl
    - libwww-perl
